#!/bin/bash
set -e
home=`dirname $(readlink -e $0)`
call="$home/call"

declare -A arm_dirs
arm_dirs=(
    [backward]=0 [forward]=1 [stop]=2
)

declare -A delays
delays=(
    [0]=0 [1]=1 [10]=2 [50]=3 [100]=4
)

function help() {
    echo "Commands: rotate <arm_dir> | step <steps> | stop | position | enable | disable | set_max <freq> | get_max | set_timer <timer> | set_delay <delay>"
    echo "arm_dir: ${!arm_dirs[@]}"
    echo "steps: positive/negative integer"
    echo "freq, timer: positive 16 bit integer"
    echo "delay: 0, 1, 10, 50, 100"
    exit 1
}

if [ $# = 1 -o $# = 2 ]; then
    command=$1
    command_name=tank_arm_$command
    if [ $# = 1 ]; then
        case $command in
            stop | position | enable | disable | get_max) ;;
            *) help ;;
        esac
    elif [ $# = 2 ]; then
        param=$2
        if [ $command == set_timer ]; then
            test $param -lt $((2**16)) -a $param -gt 0 || { echo "<freq> out of bounds 0..2^16"; help; }
            timer=`printf '%04x' $param`

            # Split the 16-bit hex-value into two separate bytes
            timer_high=${timer:0:2}
            timer_low=${timer: -2}

            params="-p $timer_low -p $timer_high"
        elif [ $command == set_max ]; then
            test $param -lt $((2**16)) -a $param -gt 0 || { echo "<freq> out of bounds 0..2^16"; help; }
            freq=`printf '%04x' $param`

            # Split the 16-bit hex-value into two separate bytes
            freq_high=${freq:0:2}
            freq_low=${freq: -2}

            params="-p $freq_low -p $freq_high"
        elif [ $command == step ]; then
            test $param -lt $((2**31)) -a $param -gt -$((2**31)) || { echo "<steps> out of bounds -2^31..2^31"; help; }
            steps=`printf '%08x' $param`

            # Split the 32-bit hex-value into four separate bytes
            param3=${steps: -8:2}
            param2=${steps: -6:2}
            param1=${steps: -4:2}
            param0=${steps: -2:2}

            params="-p $param0 -p $param1 -p $param2 -p $param3"
        elif [ $command == rotate ]; then
            arm_dir=${arm_dirs[$param]}
            test -n "$arm_dir" || { echo "Unknown arm_dir: $param"; help; }
            dirstr=`printf '%04x' $arm_dir`

            # Split the 16-bit hex-value into two separate bytes
            dir_high=${dirstr:0:2}
            dir_low=${dirstr: -2}

            params="-p $dir_low -p $dir_high"
        elif [ $command == set_delay ]; then
            delay=${delays[$param]}
            test -n "$delay" || { echo "Unknown delay: $param"; help; }
            delaystr=`printf '%04x' $delay`

            # Split the 16-bit hex-value into two separate bytes
            delay_high=${delaystr:0:2}
            delay_low=${delaystr: -2}

            params="-p $delay_low -p $delay_high"
        else
            help
        fi
    fi
else
    help
fi

$call $command_name arm $params
