#!/bin/bash
set -e
home=`dirname $(readlink -e $0)`

THRESHOLD=10000
DIFF_THRESHOLD=2000
left=0
right=0

while true; do
	read newleft newright
	test -n "$newleft" -a -n "$newright" || continue

	absleft=${newleft#-}
	absright=${newright#-}
	test "$absleft" -lt "$THRESHOLD" && newleft=0
	test "$absright" -lt "$THRESHOLD" && newright=0

	leftdiff=$((left-newleft))
	rightdiff=$((right-newright))
	if [ ${leftdiff#-} -gt "$DIFF_THRESHOLD" -o ${rightdiff#-} -gt "$DIFF_THRESHOLD" ]; then
		left=$newleft
		right=$newright
		echo "$left $right"
	fi
done
