#!/bin/bash
home="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$home/functions"
leds="$home/leds"
power="$home/power"
reset="$home/hard_reset"

function log() {
    >&2 echo " ===== `date +'%F %T'` - $@"
}

declare -A devices
devices=(
    [driver]=green2
    #[arm]=green3
)
BBB_LED=green1
TOTAL_AVRS=$((${#devices[@]} + 1))

log "Booting"
"$power" off
"$reset" off

function check() {
    log "Checking $1..."
    twi_call query_init_status $1
}

function tank_shutdown() {
    log "Shutting down"
    "$power" off
}

trap 'tank_shutdown' EXIT

function check_system() {
    log "Checking AVRs..."
    booted=0
    for device in "${!devices[@]}"; do
        led=${devices[$device]}
        if check $device; then
            "$leds" $led on
            booted=$((booted+1))
        else
            "$leds" $led blink_fast
        fi
    done
    "$leds" $BBB_LED flash && booted=$((booted+1))
    if [ $booted = $TOTAL_AVRS ]; then
        log "All $booted AVRs booted, enabling motors"
        "$power" on
    else
        log "$booted out of $TOTAL_AVRS AVRs booted, disabling motors"
        "$power" off
    fi
}

while true; do
    check_system
    "$reset" off # Just in case
    sleep 3
done
