#!/bin/bash

TWI_TOOL="../build-Native-speed/twi-tool.main.out"
TWI_BUS=2

declare -A TWI_DEVICES
TWI_DEVICES=(
    [io]=2c
    [driver]=2e
    [arm]=2a
)

function twi_call() {
    test -x "$TWI_TOOL" || { echo "TwiTool not found: $TWI_TOOL"; exit 1; }
    test $# -ge 2 || { echo "twi_call: need at least 2 parameters: <twi-function-name> <twi-device: one of (${!TWI_DEVICES[@]})>"; exit 1; }
    func="$1"
    device="$2"
    shift 2

    device_address=${TWI_DEVICES[$device]}
    test -n "$device_address" || { echo "Address of device $device not registered."; exit 1; }

    echo "$TWI_TOOL" -b $TWI_BUS -d $device_address -f $func $@
}

function param_u16bit() {
    param=$1
    param_name="Parameter"
    test "$param" -lt $((2**16)) -a "$param" -ge 0 || { >&2 echo "$param_name out of bounds 0..2^16"; help; }
    val=`printf '%04x' $param`

    # Split the 16-bit hex-value into two separate bytes
    param_high=${val:0:2}
    param_low=${val: -2}

    echo "-p $param_low -p $param_high"
}

function param_enum() {
    param_u16bit $@
}

function param_s32bit() {
    param="$1"
    param_name="Parameter"
    test "$param" -lt $((2**31)) -a "$param" -gt -$((2**31)) || { >&2 echo "$param_name out of bounds -2^31..2^31"; help; }
    val=`printf '%08x' $param`

    # Split the 32-bit hex-value into four separate bytes
    param3=${val: -8:2}
    param2=${val: -6:2}
    param1=${val: -4:2}
    param0=${val: -2:2}

    echo "-p $param0 -p $param1 -p $param2 -p $param3"
}
