#!/bin/bash
set -e
home=`dirname $(readlink -e $0)`
source "$home/functions"

declare -A leds
leds=(
    [yellow1]=0 [yellow2]=1 [yellow3]=2 [yellow4]=3 [yellow5]=4
    [red1]=5 [red2]=6 [red3]=7 [red4]=8 [red5]=9
    [green1]=10 [green2]=11 [green3]=12 [green4]=13 [green5]=14
    [yellow]=15 [green]=16 [red]=17
    [middle]=18 [left]=19 [right]=20
    [all]=21
)
declare -A modes
modes=(
    [on]=0 [off]=1
    [blink]=2 [blink_fast]=3
    [flash]=4 [flash_long]=5
    [run]=6 [running]=7
)

function help() {
    echo "Parameters: <leds> <mode>"
    echo "leds = ${!leds[@]}"
    echo "mode = ${!modes[@]}"
    exit 1
}

test $# = 2 || help
led=${leds[$1]}
test -n "$led" || { echo "Unknown leds: $1"; help; }
mode=${modes[$2]}
test -n "$mode" || { echo "Unknown mode: $2"; help; }

twi_call tank_io_set_leds io $(param_enum $led) $(param_enum $mode)
