#!/bin/bash
set -e
home=`dirname $(readlink -e $0)`
source "$home/functions"

function help() {
    test -n "$@" && echoerr $@
    echoerr "Parameters: [-l <left-motor-speed>] [-r right-motor-speed]"
    echoerr "motor-speed: -100..100"
    exit 1
}

left=0
right=0

while getopts "l:r:" opt; do case $opt in
    l) left="$OPTARG" ;;
    r) right="$OPTARG" ;;
    \?) help "Invalid option -$OPTARG" ;;
    :) help "Option -$OPTARG requires an argument" ;;
esac done

test $left -ge -100 -a $left -le 100 || help "Invalid -l parameter"
test $right -ge -100 -a $right -le 100 || help "Invalid -r parameter"

# Convert from -100..100 to the expanded hex-value
left=$((left*65535/100))
right=$((right*65535/100))

set_motors "$left" "$right"
