#!/bin/bash

function help() {
    >&2 echo "Need 2 parameters: <pin-nr> <hi|lo|in>"
    exit 1
}
test $# = 2 || help

PIN_NR="$1"
MODE="$2"

PIN="/sys/class/gpio/gpio$PIN_NR"
PIN_DIR="$PIN/direction"
PIN_VAL="$PIN/value"
EXPORT="/sys/class/gpio/export"

function config_gpio() {
    test -d "$PIN" && return
    echo $PIN_NR > "$EXPORT"
    test -d "$PIN" || { >&2 echo "Failed to export GPIO pin $PIN_NR on $PIN"; exit 1; }
}

function power_on() {
    echo "high" > "$PIN_DIR"
    echo "1" > "$PIN_VAL"
}

function power_off() {
    echo "low" > "$PIN_DIR"
    echo "0" > "$PIN_VAL"
}

function power_read() {
    echo "in" > "$PIN_DIR"
    cat "$PIN_VAL"
}

case "$MODE" in
    hi) config_gpio; power_on ;;
    lo) config_gpio; power_off ;;
    in) config_gpio; power_read ;;
    *) help ;;
esac
