#!/bin/bash
set -e
home=`dirname $(readlink -e $0)`
call="$home/call"

test $# == 2 || { echo "Need 2 parameters: <device> and <assumed frequency> "; exit 1; }
device=$1
ASSUMED_FREQ="$2"

function get_values() {
    device_time=`$call query_milliseconds $device`
    test $? == 0 || { echo "Command failed."; exit 1; }
    current_time=`date +%T.%3N`
    device_time=${device_time:9} # Strip "Running: " prefix
    device_millis=`date -d $device_time +%s%3N`
    current_millis=`date -d $current_time +%s%3N`
    diff_millis=$((device_millis-current_millis))
}

get_values
start_diff=$diff_millis
start_device_millis=$device_millis
start_millis=$current_millis
echo "Assumed device frequency: $ASSUMED_FREQ MHz"
while true; do
    get_values
    passed_millis=$((current_millis-start_millis))
    passed_device_millis=$((device_millis-start_device_millis))
    new_diff=$((diff_millis-start_diff))
    freq=$(bc -l <<< "$ASSUMED_FREQ * $passed_device_millis / $passed_millis")
    echo "$current_time ($passed_millis) <=> $device_time ($passed_device_millis) = $new_diff. Freq: $freq"
    if read -t 0.3; then break; fi
done
