/*
 * analog_m1284P.h
 *
 * Created: 27.04.2012 17:35:43
 *  Author: Anton
 */ 

#ifndef ANALOG_M1284P_H_
#define ANALOG_M1284P_H_

#include "analog.h"

DEFINE_ANALOG_INPUT(Analog0)
DEFINE_ANALOG_INPUT(Analog1)
DEFINE_ANALOG_INPUT(Analog2)
DEFINE_ANALOG_INPUT(Analog3)
DEFINE_ANALOG_INPUT(Analog4)
DEFINE_ANALOG_INPUT(Analog5)
DEFINE_ANALOG_INPUT(Analog6)
DEFINE_ANALOG_INPUT(Analog7)

#endif /* ANALOG_M1284P_H_ */