#ifndef TWI_SERVICE_TEST_H_
#define TWI_SERVICE_TEST_H_

#include <kernel/twi/rpc/client_functions.h>

enum {
    TEST_WRITE_VALUE_OPERATION = 10,
    TEST_READ_VALUE_OPERATION,
    TEST_INC_VALUE_OPERATION,
    TEST_RESET_VALUE_OPERATION
};

TWI_RPC_FUNCTION_VOID(test_write_value, TEST_WRITE_VALUE_OPERATION, int32_t)
TWI_RPC_FUNCTION_NOARGS(test_read_value, TEST_READ_VALUE_OPERATION, int32_t)
TWI_RPC_FUNCTION_NOTIFY(test_increment_value, TEST_INC_VALUE_OPERATION)
TWI_RPC_FUNCTION_NOTIFY(test_reset_value, TEST_RESET_VALUE_OPERATION)

#endif // TWI_SERVICE_TEST_H_
